// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package button

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "strings"

type Variant string

const (
	VariantDefault Variant = "default"
	VariantGhost   Variant = "ghost"
	VariantOutline Variant = "outline"
	VariantIcon    Variant = "icon"
)

type Props struct {
	ID         string
	Class      string
	Attributes templ.Attributes
	Variant    Variant
}

func (p *Props) classes() string {
	classes := []string{}

	switch p.Variant {
	case VariantDefault:
		classes = append(classes,
			"px-4 py-2 rounded-lg",
			"text-white bg-gray-800 hover:bg-gray-700 dark:text-gray-200 dark:bg-gray-600 dark:hover:bg-gray-500",
			"focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 dark:focus:ring-gray-400",
			"transition-all duration-200 ease-in-out",
			"shadow-sm hover:shadow-md",
			"disabled:bg-gray-400 disabled:text-gray-200 disabled:hover:bg-gray-400 disabled:shadow-none dark:disabled:bg-gray-500 dark:disabled:text-gray-300",
		)
	case VariantGhost:
		classes = append(classes,
			"px-4 py-2 rounded-lg",
			"text-gray-700 bg-transparent hover:bg-gray-100",
			"focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-400",
			"transition-all duration-200 ease-in-out",
			"disabled:text-gray-400 disabled:hover:bg-transparent disabled:shadow-none",
		)
	case VariantOutline:
		classes = append(classes,
			"px-4 py-2 rounded-lg border-2",
			"border-gray-800 text-gray-800 bg-transparent hover:bg-gray-50",
			"focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500",
			"transition-all duration-200 ease-in-out",
			"disabled:border-gray-400 disabled:text-gray-400 disabled:hover:bg-transparent disabled:shadow-none",
		)
	case VariantIcon:
		classes = append(classes,
			"p-2.5 rounded-lg",
			"text-gray-700 bg-transparent hover:bg-gray-100",
			"focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-400",
			"transition-all duration-200 ease-in-out",
			"disabled:text-gray-400 disabled:hover:bg-transparent disabled:shadow-none",
		)
	}

	return strings.Join(classes, " ") + p.Class
}

func Button(props ...Props) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		p := Props{}
		if len(props) > 0 {
			p = props[0]
		}
		var templ_7745c5c3_Var2 = []any{p.classes()}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<button id=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(p.ID)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/components/button/button.templ`, Line: 71, Col: 11}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/components/button/button.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, p.Attributes)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, ">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</button>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
